version: "2"

services:

  mongo:
    container_name: slack-token-mongo
    image: slack-token-mongo
    build: ./docker/mongo
    volumes:
      - ./data/mongo:/data/db

  redis:
      image: slack-token-redis
      container_name: slack-token-redis
      build: ./docker/redis

  app:
    image: slack-token-app
    container_name: slack-token-app
    build: ./docker/app
    volumes:
      - ./app:/var/app
    links:
      - mongo

  queue:
    image: slack-token-queue
    container_name: slack-token-queue
    build: ./docker/queue
    volumes:
      - ./app:/var/app
    links:
      - mongo
      - redis

  nginx:
    image: slack-token-nginx
    container_name: slack-token-nginx
    build: ./docker/nginx-ssl
    volumes:
      - ./fullchain.pem:/etc/letsencrypt/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
